name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            qt_version: "6.5.0"
          - os: ubuntu-latest  
            qt_version: "6.5.0"
          - os: macos-latest
            qt_version: "6.5.0"
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Qt (Windows/Mac)
      if: runner.os != 'Linux'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}
        host: ${{ runner.os }}
        target: desktop
        modules: qtnetwork qtwidgets
        
    - name: Install Qt (Linux)
      if: runner.os == 'Linux'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}
        host: linux
        target: desktop
        modules: qtnetwork qtwidgets
        
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0
        
    - name: Configure and Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
      
    - name: Package Windows
      if: runner.os == 'Windows'
      run: |
        cd build/Release
        windeployqt CyberScanner.exe
        Compress-Archive -Path * -DestinationPath ../CyberScanner-Windows.zip
        
    - name: Package Linux
      if: runner.os == 'Linux'
      run: |
        cd build
        mkdir package
        cp cyberscanner package/
        tar -czf CyberScanner-Linux.tar.gz -C package .
        
    - name: Package macOS
      if: runner.os == 'macOS'
      run: |
        cd build
        macdeployqt CyberScanner.app -dmg
        mv CyberScanner.dmg CyberScanner-macOS.dmg
        
    - name: Upload Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: CyberScanner-Windows
        path: build/CyberScanner-Windows.zip
        
    - name: Upload Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: CyberScanner-Linux
        path: build/CyberScanner-Linux.tar.gz
        
    - name: Upload macOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: CyberScanner-macOS
        path: build/CyberScanner-macOS.dmg
