name: Test Build

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev cmake build-essential
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
        
    - name: Test
      run: |
        ls -la build/
        file build/cyberscanner || echo "Binary not found"
